# Generated by Django 3.1.7 on 2021-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20210417_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pass_threshold',
            field=models.SmallIntegerField(default=0),
        ),
    ]
