# Generated by Django 3.1.7 on 2021-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20210430_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='aggregation_method',
            field=models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average'), ('WAVG', 'Weighted Average')], default='AVG', max_length=4),
        ),
    ]
