# Generated by Django 3.1.7 on 2021-03-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_is_female'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.defaultuser')),
                ('title', models.CharField(choices=[('PROF', 'professor'), ('MSc', 'master of science'), ('BoS', 'bachelor of science')], default='BoS', max_length=4)),
            ],
        ),
    ]
