# Generated by Django 3.1.7 on 2021-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_female',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1),
        ),
    ]
