# Generated by Django 3.1.7 on 2021-04-01 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210329_2243'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_min', models.SmallIntegerField()),
                ('grade_max', models.SmallIntegerField()),
                ('is_extra', models.BooleanField()),
                ('parent_task_id', models.IntegerField()),
                ('weight', models.FloatField()),
                ('deadline', models.DateTimeField()),
                ('aggregation_method', models.CharField(choices=[('AVG', 'Average'), ('WAVG', 'Weighted Average')], default='AVG', max_length=4)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.course')),
            ],
        ),
    ]
