# Generated by Django 3.1.7 on 2021-04-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_course_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.task'),
        ),
    ]
