# Generated by Django 3.1.7 on 2021-04-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210329_2243'),
        ('tracker', '0004_auto_20210403_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.IntegerField(choices=[(1, 'Diamond'), (2, 'Gold'), (3, 'Silver'), (4, 'Bronze')])),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=models.SET(-1), to='tracker.course')),
                ('issued_by', models.ForeignKey(on_delete=models.SET(-1), to='accounts.teacher')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('task_id', models.ForeignKey(on_delete=models.SET(-1), to='tracker.task')),
            ],
        ),
    ]
