# Generated by Django 3.1.7 on 2021-04-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210329_2243'),
        ('tracker', '0005_grade_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='parent_task_id',
            new_name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='course_id',
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.teacher'),
        ),
    ]
