# Generated by Django 3.1.7 on 2021-04-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20210418_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('ALL', 'pass all tasks'), ('MAX', 'get 100% from task x'), ('THRESH', 'get x% from course'), ('BONUS', 'complete bonus task'), ('STREAK', '100% from 3 tasks within a month')], max_length=10)),
                ('args', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.course')),
            ],
        ),
    ]
