# Generated by Django 3.1.7 on 2021-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210329_2243'),
        ('tracker', '0014_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='student',
            field=models.ManyToManyField(blank=True, to='accounts.Student'),
        ),
    ]
