# Generated by Django 3.1.7 on 2021-04-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_achievement_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='args',
            field=models.CharField(default='', max_length=100),
        ),
    ]
