# Generated by Django 3.1.7 on 2021-05-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20210504_2149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('course', 'kind', 'args')},
        ),
    ]
