# Generated by Django 3.1.7 on 2021-05-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20210510_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='issued_at',
        ),
    ]
