# Generated by Django 3.1.7 on 2021-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_remove_achievement_issued_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mock',
        ),
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='achievement', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
