# Generated by Django 3.1.7 on 2021-05-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210329_2243'),
        ('tracker', '0022_auto_20210517_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('task', 'student')},
        ),
    ]
